# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/wge_auth_download_strategy"
class GitopsEe < Formula
  desc "GitOps support for Kubernetes"
  homepage "https://docs.gitops.weave.works/docs/getting-started"
  version "0.9.2-rc.1"
  depends_on :macos

  on_macos do
    url "https://artifacts.wge.dev.weave.works/releases/bin/0.9.2-rc.1/gitops-darwin-amd64", :using => WGEAuthDownloadStrategy
    sha256 "75dfdc8a71ebdad92889ea88ccf85815880dacd116c23a032368a0fc75030334"

    def install
      bin.install "gitops"
      # Install bash completion
      output = Utils.popen_read("#{bin}/gitops completion bash")
      (bash_completion/"gitops").write output

      # Install zsh completion
      output = Utils.popen_read("#{bin}/gitops completion zsh")
      (zsh_completion/"_gitops").write output
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the GitopsEe
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end
end
